From Stdlib Require Import Setoid
  setoid_ring.Field Lia Vector Utf8
  Psatz Bool Pnat BinNatDef BinPos List.
From Algebra Require Import
  Hierarchy Group Monoid
  Field Integral_domain
  Ring Vector_space.
From Utility Require Import Util.
From Compiler Require Import LinearRelation LeafValidity
  Degeneracy IncidenceDecide.

Import VectorNotations.

(** * The axis on which no checker can be complete

    A leaf can fail its purpose in two independent ways.  It can fail
    to determine its witness, and Degeneracy.v, IncidenceComplete.v
    and IncidenceDecide.v settle that axis completely: the incidence
    system is exactly the structurally visible part of the kernel, and
    a certificate decides membership.

    It can also be *vacuous*, satisfied by a witness anybody could
    write down, or *unsatisfiable*, satisfied by nothing.  This file
    is about that second axis, and its main content is that the same
    treatment is not available there, together with the fragments that
    are.

    ** Why the second axis does not close

    [leaf_satisfiability_is_discrete_log] is the obstruction, stated
    as an equivalence rather than as an aspiration: for a one-by-one
    leaf, asking whether the statement has a witness at all is asking
    whether the target lies in the subgroup generated by the base.
    That is the discrete logarithm problem.  A checker that decided
    leaf satisfiability would decide it, so no checker does, and every
    condition on this axis is a one-directional sufficient condition
    with no converse.

    ** The fragments that hold

    [leaf_vacuous_iff_neutral_targets] pins down exactly when the
    all-zero witness works: when every target is the neutral element,
    and not otherwise.  [empty_leaf_is_vacuous] records the degenerate
    case of no equations at all, which [leaf_validb] accepts.
    [dead_row_unsatisfiable] records the opposite failure, an equation
    whose bases are all neutral and whose target is not.

    ** A condition that is too strong

    Putting the first of those next to [leaf_validb] shows the
    checker of LeafValidity.v is not merely incomplete but wrong in
    one direction.  It demands that *every* target be off the neutral
    element, while vacuity needs *all* of them to be on it.  A leaf
    with one neutral target among several is neither vacuous nor
    undetermined, and [target_live_rejects_a_sound_leaf] exhibits one:
    the checker rejects a statement that is sound on both axes.  The
    condition should be weakened to match the theorem that justifies
    it. *)
Section Vacuity.

  Context
    {F : Type}
    {zero one : F}
    {add mul sub div : F -> F -> F}
    {opp inv : F -> F}
    {Fdec : forall x y : F, {x = y} + {x <> y}}.

  Context
    {G : Type}
    {gid : G}
    {ginv : G -> G}
    {gop : G -> G -> G}
    {gpow : G -> F -> G}
    {Gdec : forall x y : G, {x = y} + {x <> y}}.

  Context
    {Hvec : @vector_space F (@eq F) zero one add mul sub
      div opp inv G (@eq G) gid ginv gop gpow}.

  Add Field field : (@field_theory_for_stdlib_tactic F
    eq zero one opp add mul sub inv div vector_space_field).

  #[local] Notation row_evalC := (@row_eval F G gid gop gpow).
  #[local] Notation mat_evalC := (@mat_eval F G gid gop gpow).
  #[local] Notation incidence_zeroC := (@incidence_zero F zero add G gid Gdec).
  #[local] Notation wzeroC := (@wzero F zero).

  (** ** Exactly when the all-zero witness works

      One direction is [neutral_targets_are_free] of LeafValidity.v.
      The other is what that file did not state, and it is what shows
      its second condition is stronger than its own justification. *)
  Theorem leaf_vacuous_iff_neutral_targets :
    ∀ (m n : nat) (mat : Vector.t (Vector.t G n) m) (pub : Vector.t G m),
    mat_evalC mat (wzeroC n) = pub <-> (∀ i : Fin.t m, Vector.nth pub i = gid).
  Proof.
    intros m n mat pub; split.
    - intros hzero i.
      rewrite <- hzero.
      unfold mat_eval; rewrite (Vector.nth_map _ _ i i eq_refl).
      apply row_eval_zero.
    - intro hall; apply neutral_targets_are_free; exact hall.
  Qed.

  (** ** A leaf with no equations

      A matrix of zero rows imposes nothing, so every witness
      satisfies it.  With zero secrets as well, [leaf_validb] accepts:
      no column is dead because there is no column, and no target is
      neutral because there is no target. *)
  Theorem empty_leaf_is_vacuous :
    ∀ (n : nat) (mat : Vector.t (Vector.t G n) 0) (pub : Vector.t G 0)
      (v : Vector.t F n),
    mat_evalC mat v = pub.
  Proof.
    intros n mat pub v.
    rewrite (vector_inv_0 (mat_evalC mat v)), (vector_inv_0 pub); reflexivity.
  Qed.

  Theorem empty_leaf_accepted :
    @leaf_validb G gid Gdec 0 0 [] [] = true.
  Proof. reflexivity. Qed.

  (** ** An equation nobody can satisfy

      A row whose bases are all neutral evaluates to the neutral
      element whatever the witness, so if its target is anything else
      the leaf has no witness at all.  This is not unsoundness, but a
      verifier taking statements off the wire should still refuse it,
      and [leaf_validb] does not. *)
  Theorem dead_row_unsatisfiable :
    ∀ (m n : nat) (mat : Vector.t (Vector.t G n) m) (pub : Vector.t G m)
      (i : Fin.t m),
    (∀ j : Fin.t n, Vector.nth (Vector.nth mat i) j = gid) ->
    Vector.nth pub i <> gid ->
    ∀ v : Vector.t F n, mat_evalC mat v <> pub.
  Proof.
    intros m n mat pub i hdead hlive v hbad.
    apply hlive.
    rewrite <- hbad.
    unfold mat_eval; rewrite (Vector.nth_map _ _ i i eq_refl).
    apply row_eval_all_gid; exact hdead.
  Qed.

  (** ** Why the axis does not close

      Whether a one-by-one leaf has a witness is whether the target
      lies in the subgroup generated by the base.  A checker deciding
      leaf satisfiability would decide discrete logarithms, so none
      does, and every condition above is sufficient without being
      necessary. *)
  Theorem leaf_satisfiability_is_discrete_log :
    ∀ (g P : G),
    (∃ v : Vector.t F 1, mat_evalC [[g]] v = [P]) <-> (∃ x : F, gpow g x = P).
  Proof.
    intros g P; split.
    - intros (v & hv).
      destruct (vector_inv_S v) as (x & v' & hx); subst v.
      rewrite (vector_inv_0 v') in hv.
      exists x.
      assert (hrow : row_evalC [g] [x] = P)
        by (change P with (Vector.nth ([P] : Vector.t G 1) Fin.F1);
            rewrite <- hv; unfold mat_eval;
            rewrite (Vector.nth_map _ _ Fin.F1 Fin.F1 eq_refl); reflexivity).
      rewrite row_eval_cons, row_eval_nil, right_identity in hrow.
      exact hrow.
    - intros (x & hx).
      exists [x].
      apply Vector.eq_nth_iff; intros p q hpq; subst q.
      rewrite (fin1_is_F1 p).
      unfold mat_eval; rewrite (Vector.nth_map _ _ Fin.F1 Fin.F1 eq_refl).
      cbn [Vector.nth Vector.caseS].
      rewrite row_eval_cons, row_eval_nil, right_identity; cbn; exact hx.
  Qed.

  (** ** A leaf the checker of LeafValidity.v wrongly rejects

      [target_live] asks that no target be neutral, but the theorem
      justifying it,  [neutral_targets_are_free], needs every target
      to be neutral before anything goes wrong.  The gap is real: the
      leaf below has one neutral target and one live one, is not
      satisfied by the all-zero witness, has only the zero solution to
      its incidence system, and is rejected all the same. *)
  Theorem target_live_rejects_a_sound_leaf :
    ∀ (g P : G),
    g <> gid -> P <> gid ->
    (* rejected *)
    @leaf_validb G gid Gdec 2 1 [[g]; [g]] [gid; P] = false
    (* not vacuous *)
    ∧ mat_evalC [[g]; [g]] (wzeroC 1) <> [gid; P]
    (* and its witness is determined *)
    ∧ (∀ v : Vector.t F 1, incidence_zeroC [[g]; [g]] v -> v = wzeroC 1).
  Proof.
    intros g P hg hP; split; [| split].
    - (* the second condition fails on the first target *)
      destruct (@leaf_validb G gid Gdec 2 1 [[g]; [g]] [gid; P]) eqn:hb;
        [| reflexivity].
      exfalso.
      destruct (proj1 (leaf_validb_spec 2 1 [[g]; [g]] [gid; P]) hb)
        as (_ & htl).
      exact (htl Fin.F1 eq_refl).
    - intro hbad.
      apply hP.
      pose proof (proj1 (leaf_vacuous_iff_neutral_targets 2 1 [[g]; [g]]
                           [gid; P]) hbad (Fin.FS Fin.F1)) as h.
      cbn in h; exact h.
    - apply (separating_row_determines 2 1 [[g]; [g]] Fin.F1).
      + intro j; rewrite (fin1_is_F1 j); cbn; exact hg.
      + intros j j' hne; exfalso; apply hne.
        rewrite (fin1_is_F1 j), (fin1_is_F1 j'); reflexivity.
  Qed.

End Vacuity.
